"""QR payload decoding and validation utility.

Decodes self-contained QR payloads embedded in box/item QR codes.

Supports three input formats:

1. JSON payload (box-level label):
   {"id": "RB7FJE", "sku": "ITEM-001", "qty": 50, "batch": "BATCH-2025-01"}

2. Product authentication URL (generated by the QR block system):
   https://{org}.{domain}/g/{gtin}/s/{serial}/{timestamp}?c={signature}

3. Bare serial number string (e.g. "RB7FJE"):
   Looked up directly in product_items. Useful when a scanner only emits
   the serial without the surrounding URL.

For formats (2) and (3) the serial is resolved against ProductItem to
derive the SKU. qty defaults to 1 and batch defaults to the serial number
since these are unit-level scans.

Requirements: 4.1, 4.2, 4.3, 5.3
"""

import json
import re
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

from app.core.exceptions import ValidationError

if TYPE_CHECKING:
    from sqlalchemy.orm import Session


# Matches:
#   https://<anything>/g/<gtin>/s/<serial>/<timestamp>?c=<sig>
#   https://<anything>/g/<gtin>/s/<serial>           (unsigned, no nonce)
_QR_URL_PATTERN = re.compile(
    r"https?://[^/]+/g/[^/]+/s/(?P<serial>[^/?]+)(?:/(?P<nonce>[^?]+))?"  # unsigned also
)

# GS1 Digital Link SGTIN:
#   https://<anything>/01/<gtin>/21/<serial>
#   https://<anything>/01/<gtin>/10/<lot>/21/<serial>
_GS1_SGTIN_URL_PATTERN = re.compile(
    r"https?://[^/]+/01/[^/]+(?:/10/[^/]+)?/21/(?P<serial>[^/?]+)"
)

# Bare serial number — alphanumeric plus dashes/underscores, 4–75 chars.
# Anything outside this set falls through to the JSON branch so we still
# surface a helpful error for malformed payloads.
_BARE_SERIAL_PATTERN = re.compile(r"^[A-Za-z0-9_-]{4,75}$")


@dataclass
class QRPayload:
    """Structured representation of a decoded QR code payload.

    Attributes:
        id: Unique QR code identifier (serial number)
        sku: Stock Keeping Unit identifier (non-empty string)
        qty: Item quantity (positive integer)
        batch: Batch number (non-empty string)
        packaging_unit_qr_id: Optional QR identifier that resolves to an
            item_packaging_units.qr_identifier for multi-UOM support.
    """

    id: str
    sku: str
    qty: int
    batch: str
    packaging_unit_qr_id: str | None = field(default=None)


def _resolve_serial(serial: str, db: "Session | None") -> QRPayload:
    """Look up a ProductItem by serial number and build a unit-level QRPayload.

    qty defaults to 1 and batch defaults to the serial since serial-only
    scans carry no batch metadata.
    """
    if db is None:
        raise ValidationError(
            message="Invalid QR payload: cannot resolve serial without database",
            details=[
                {
                    "field": "qr_data",
                    "reason": "Pass db session to decode_qr_payload to resolve serial-only QR codes",
                }
            ],
        )

    # Local import to avoid a circular dependency at module load time.
    from app.models.product_item import ProductItem

    item = (
        db.query(ProductItem)
        .filter(
            ProductItem.serial_number == serial,
            ProductItem.deleted_at.is_(None),
        )
        .first()
    )

    if item is None:
        raise ValidationError(
            message=f"QR code not found: serial '{serial}' does not match any product",
            details=[
                {
                    "field": "qr_data",
                    "reason": f"No ProductItem found for serial number '{serial}'",
                }
            ],
        )

    # Resolve SKU from the linked QR product (gtin → name → serial fallback)
    sku = serial
    if item.product:
        sku = item.product.gtin or item.product.name or serial

    return QRPayload(
        id=serial,
        sku=sku,
        qty=1,
        batch=serial,
    )


def _decode_url_payload(qr_data: str, db: "Session | None") -> QRPayload:
    """Extract a QRPayload from a product authentication URL.

    Supports GS1 Digital Link SGTIN (/01/{gtin}/21/{serial}) and the legacy
    /g/{gtin}/s/{serial} format for backward compatibility.
    """
    match = _GS1_SGTIN_URL_PATTERN.search(qr_data) or _QR_URL_PATTERN.search(qr_data)
    if not match:
        raise ValidationError(
            message="Invalid QR payload: URL format not recognised",
            details=[
                {
                    "field": "qr_data",
                    "reason": (
                        "Expected URL format: "
                        "https://<domain>/01/<gtin>/21/<serial> "
                        "or https://<domain>/g/<gtin>/s/<serial>[/<nonce>]"
                    ),
                }
            ],
        )

    return _resolve_serial(match.group("serial"), db)


def decode_qr_payload(qr_data: str, db: "Session | None" = None) -> QRPayload:  # noqa: C901
    """Decode and validate a QR payload string.

    Accepts three formats:
    - Product authentication URL (GS1): https://.../01/{gtin}/21/{serial}?c={sig}&n={nonce}
      or legacy: https://.../g/{gtin}/s/{serial}/{nonce}?c={sig}
    - Bare serial number: e.g. "RB7FJE" (4–75 alphanumeric / dash / underscore)
    - JSON string: {"id": "...", "sku": "...", "qty": N, "batch": "..."}

    Args:
        qr_data: Raw string from the scanned QR code.
        db: Optional SQLAlchemy session. Required when qr_data is a URL or
            bare serial (so the ProductItem can be resolved).

    Returns:
        QRPayload: Validated and structured payload data.

    Raises:
        ValidationError: If the payload cannot be decoded or is invalid.
    """
    if not qr_data or not qr_data.strip():
        raise ValidationError(
            message="Invalid QR payload: empty input",
            details=[{"field": "qr_data", "reason": "qr_data must not be empty"}],
        )

    qr_data = qr_data.strip()

    # ── URL format detection ──────────────────────────────────────────────────
    if qr_data.startswith("http://") or qr_data.startswith("https://"):
        return _decode_url_payload(qr_data, db)

    # ── Bare serial number (no JSON, no URL) ──────────────────────────────────
    # Matched before the JSON branch so callers get a clearer error than a
    # JSON parse failure when they send something like "RB7FJE".
    if _BARE_SERIAL_PATTERN.match(qr_data):
        return _resolve_serial(qr_data, db)

    # ── JSON format ───────────────────────────────────────────────────────────
    try:
        data = json.loads(qr_data)
    except (json.JSONDecodeError, TypeError) as e:
        raise ValidationError(
            message="Invalid QR payload: not valid JSON",
            details=[{"field": "qr_data", "reason": f"JSON parse error: {str(e)}"}],
        )

    if not isinstance(data, dict):
        raise ValidationError(
            message="Invalid QR payload: expected a JSON object",
            details=[{"field": "qr_data", "reason": "Payload must be a JSON object"}],
        )

    errors = []

    qr_id = data.get("id")
    if qr_id is None:
        errors.append({"field": "id", "reason": "Missing required field 'id'"})
    elif not isinstance(qr_id, str) or not qr_id.strip():
        errors.append(
            {"field": "id", "reason": "Field 'id' must be a non-empty string"}
        )

    sku = data.get("sku")
    if sku is None:
        errors.append({"field": "sku", "reason": "Missing required field 'sku'"})
    elif not isinstance(sku, str) or not sku.strip():
        errors.append(
            {"field": "sku", "reason": "Field 'sku' must be a non-empty string"}
        )

    qty = data.get("qty")
    if qty is None:
        errors.append({"field": "qty", "reason": "Missing required field 'qty'"})
    elif not isinstance(qty, int) or isinstance(qty, bool):
        errors.append({"field": "qty", "reason": "Field 'qty' must be an integer"})
    elif qty <= 0:
        errors.append(
            {"field": "qty", "reason": "Field 'qty' must be a positive integer"}
        )

    batch = data.get("batch")
    if batch is None:
        errors.append({"field": "batch", "reason": "Missing required field 'batch'"})
    elif not isinstance(batch, str) or not batch.strip():
        errors.append(
            {"field": "batch", "reason": "Field 'batch' must be a non-empty string"}
        )

    if errors:
        raise ValidationError(
            message="Invalid QR payload: validation failed",
            details=errors,
        )

    return QRPayload(
        id=qr_id.strip(),
        sku=sku.strip(),
        qty=qty,
        batch=batch.strip(),
        packaging_unit_qr_id=data.get("packaging_unit_qr_id") or None,
    )
