"""Module classification for audited core-service tables.

The audit UI groups events by business module. ``table_to_module`` maps a
``table_name`` to one of the modules below; ``tables_for_module`` reverses it
for the ``module`` filter on ``GET /admin/audit-logs``.

Notes:
- Users and Roles activity (login/logout, role assignment) is recorded by the
  identity service, not core-service, so those modules are sparse here
  (``Users`` has only ``warehouse_users``; ``Roles`` is empty).
- ``Other`` holds marketing / communication / public-QR tables that don't fit
  the seven business modules.
- When a new table is added, add it to ``_MODULE_TABLES`` — unmapped tables
  fall back to ``Other`` in responses but are not matched by the ``Other``
  filter until listed here.
"""

MODULES: list[str] = [
    "Inventory",
    "WMS",
    # "Revenue",
    "QSeal",
    "Users",
    "Roles",
    # "Settings",
    # "Other",
]

_MODULE_TABLES: dict[str, list[str]] = {
    "Inventory": [
        "batches",
        "brands",
        "item_groups",
        "item_packaging_units",
        "item_prices",
        "item_suppliers",
        "items",
        "packaging_types",
        "product_items",
        "product_sku_attribute_values",
        "product_skus",
        "products",
        "serial_no_history",
        "serial_nos",
        "stock_entries",
        "stock_entry_items",
        "stock_levels",
        "stock_movements",
        "stock_reconciliation_items",
        "stock_reconciliations",
        "stock_settings",
        "suppliers",
        "uom_conversions",
        "uoms",
        "variant_attribute_values",
        "variant_attributes",
        "warranties",
        "warranty_periods",
    ],
    "WMS": [
        "asn_order_items",
        "asn_order_serial_lines",
        "asn_orders",
        "bin_reservations",
        "bin_stock_levels",
        "delivery_note_items",
        "delivery_notes",
        "dispatch_records",
        "gate_verification_items",
        "gate_verification_sessions",
        "handling_units",
        "location_allocations",
        "location_scans",
        "material_request_lines",
        "material_requests",
        "outbound_order_items",
        "outbound_orders",
        "packing_slip_items",
        "packing_slips",
        "pending_warehouse_assignments",
        "pick_exceptions",
        "pick_idempotency_keys",
        "pick_list_items",
        "pick_lists",
        "purchase_receipt_items",
        "purchase_receipts",
        "put_away_list_items",
        "put_away_lists",
        "put_away_rules",
        "quality_inspection_parameters",
        "quality_inspection_readings",
        "quality_inspection_templates",
        "quality_inspections",
        "receiving_slip_items",
        "receiving_slips",
        "scan_session_items",
        "scan_sessions",
        "vehicle_arrivals",
        "vehicles",
        "warehouse_floor_plans",
        "warehouse_locations",
        "warehouses_extended",
        "wms_devices",
        "worker_sessions",
        "worker_tasks",
    ],
    # "Revenue": [
    #     "account_balances",
    #     "accounts",
    #     "bank_account_history",
    #     "bank_accounts",
    #     "bank_reconciliations",
    #     "bank_transactions",
    #     "charge_templates",
    #     "currency_masters",
    #     "customers",
    #     "default_accounts",
    #     "exchange_rates",
    #     "invoice_items",
    #     "invoices",
    #     "journal_entries",
    #     "journal_entry_lines",
    #     "landed_cost_vouchers",
    #     "payment_entries",
    #     "payment_references",
    #     "payments",
    #     "purchase_order_lines",
    #     "purchase_orders",
    #     "quotation_items",
    #     "quotations",
    #     "reminder_configs",
    #     "reminder_logs",
    #     "return_receipt_note_events",
    #     "return_receipt_note_items",
    #     "return_receipt_notes",
    #     "return_registration_items",
    #     "return_registrations",
    #     "return_session_items",
    #     "return_sessions",
    #     "rfq_lines",
    #     "rfq_suppliers",
    #     "rfqs",
    #     "sales_order_items",
    #     "sales_orders",
    #     "supplier_quotes",
    #     "tax_rules",
    #     "tax_templates",
    #     "transaction_charge_breakdown",
    #     "transaction_tax_breakdown",
    # ],
    "QSeal": [
        "qr_activation_parameters",
        "qr_activation_tracks",
        "qr_blocks",
        "qr_credit_balance",
        "qr_credit_ledger",
        "qr_credit_reservations",
        "qr_credit_usage",
        "qr_cta_configs",
        "qr_product_settings",
        "qr_products",
        "qr_scan_events",
        "qr_scan_interactions",
        "qseal_activation_requests",
        "qseal_parameters",
        "qseal_tracks",
    ],
    "Users": [
        "warehouse_users",
    ],
    "Roles": [],
    # "Settings": [
    #     "admin_notifications",
    #     "bulk_export_jobs",
    #     "bulk_import_jobs",
    #     "destination_markets",
    #     "document_numbering_config",
    #     "document_sequence_counter",
    #     "erp_sync_messages",
    #     "feature_flags",
    #     "message_templates",
    #     "notifications",
    #     "shopify_configs",
    #     "system_config",
    # ],
    # "Other": [
    #     "brand_industries",
    #     "brand_trust_answers",
    #     "brand_trust_assessments",
    #     "brand_trust_questions",
    #     "bulk_message_jobs",
    #     "campaign_leads",
    #     "campaign_tags",
    #     "campaigns",
    #     "communication_logs",
    #     "coupon_durations",
    #     "coupon_unlock_logs",
    #     "coupons",
    #     "external_coupons",
    #     "landing_page_configs",
    #     "message_credits",
    #     "meta_campaigns",
    #     "play2win_prizes",
    #     "public_submissions",
    #     "rcs_credentials",
    #     "rcs_reports",
    #     "rcs_templates",
    #     "scheduled_messages",
    #     "short_urls",
    #     "sms_reports",
    #     "web_campaigns",
    #     "whatsapp_reports",
    # ],
}

# table_name -> module (flattened, for row-level lookup)
TABLE_MODULE_MAP: dict[str, str] = {
    table: module for module, tables in _MODULE_TABLES.items() for table in tables
}


def table_to_module(table_name: str) -> str:
    """Return the business module for a table, defaulting to ``Other``."""
    return TABLE_MODULE_MAP.get(table_name, "Other")


def tables_for_module(module: str) -> list[str]:
    """Return the core tables belonging to *module* (empty for unknown)."""
    return list(_MODULE_TABLES.get(module, []))
